# Stage 1: Build
FROM golang:alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/api ./cmd/api

# Stage 2: Runtime
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/api /app/api
EXPOSE 8080
CMD ["/app/api"]