# Stage 1: Build
FROM golang:alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/reporting ./proto/reporting

# Stage 2: Runtime
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/reporting /app/reporting
EXPOSE 50051
CMD ["/app/reporting"]
