// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/reporting/v1/reporting.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAccountSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSummaryRequest) Reset() {
	*x = GetAccountSummaryRequest{}
	mi := &file_proto_reporting_v1_reporting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSummaryRequest) ProtoMessage() {}

func (x *GetAccountSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_v1_reporting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporting_v1_reporting_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountSummaryRequest) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type GetAccountSummaryResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AccountId              int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CurrentBalanceMinor    int64                  `protobuf:"varint,2,opt,name=current_balance_minor,json=currentBalanceMinor,proto3" json:"current_balance_minor,omitempty"`
	TotalDepositsMinor     int64                  `protobuf:"varint,3,opt,name=total_deposits_minor,json=totalDepositsMinor,proto3" json:"total_deposits_minor,omitempty"`
	TotalWithdrawalsMinor  int64                  `protobuf:"varint,4,opt,name=total_withdrawals_minor,json=totalWithdrawalsMinor,proto3" json:"total_withdrawals_minor,omitempty"`
	TotalTransfersInMinor  int64                  `protobuf:"varint,5,opt,name=total_transfers_in_minor,json=totalTransfersInMinor,proto3" json:"total_transfers_in_minor,omitempty"`
	TotalTransfersOutMinor int64                  `protobuf:"varint,6,opt,name=total_transfers_out_minor,json=totalTransfersOutMinor,proto3" json:"total_transfers_out_minor,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetAccountSummaryResponse) Reset() {
	*x = GetAccountSummaryResponse{}
	mi := &file_proto_reporting_v1_reporting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSummaryResponse) ProtoMessage() {}

func (x *GetAccountSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporting_v1_reporting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporting_v1_reporting_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountSummaryResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetCurrentBalanceMinor() int64 {
	if x != nil {
		return x.CurrentBalanceMinor
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetTotalDepositsMinor() int64 {
	if x != nil {
		return x.TotalDepositsMinor
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetTotalWithdrawalsMinor() int64 {
	if x != nil {
		return x.TotalWithdrawalsMinor
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetTotalTransfersInMinor() int64 {
	if x != nil {
		return x.TotalTransfersInMinor
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetTotalTransfersOutMinor() int64 {
	if x != nil {
		return x.TotalTransfersOutMinor
	}
	return 0
}

var File_proto_reporting_v1_reporting_proto protoreflect.FileDescriptor

const file_proto_reporting_v1_reporting_proto_rawDesc = "" +
	"\n" +
	"\"proto/reporting/v1/reporting.proto\x12\freporting.v1\"9\n" +
	"\x18GetAccountSummaryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\"\xcc\x02\n" +
	"\x19GetAccountSummaryResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x122\n" +
	"\x15current_balance_minor\x18\x02 \x01(\x03R\x13currentBalanceMinor\x120\n" +
	"\x14total_deposits_minor\x18\x03 \x01(\x03R\x12totalDepositsMinor\x126\n" +
	"\x17total_withdrawals_minor\x18\x04 \x01(\x03R\x15totalWithdrawalsMinor\x127\n" +
	"\x18total_transfers_in_minor\x18\x05 \x01(\x03R\x15totalTransfersInMinor\x129\n" +
	"\x19total_transfers_out_minor\x18\x06 \x01(\x03R\x16totalTransfersOutMinor2x\n" +
	"\x10ReportingService\x12d\n" +
	"\x11GetAccountSummary\x12&.reporting.v1.GetAccountSummaryRequest\x1a'.reporting.v1.GetAccountSummaryResponseB5Z3github.com/reggae-krk/payflow/internal/reporting/pbb\x06proto3"

var (
	file_proto_reporting_v1_reporting_proto_rawDescOnce sync.Once
	file_proto_reporting_v1_reporting_proto_rawDescData []byte
)

func file_proto_reporting_v1_reporting_proto_rawDescGZIP() []byte {
	file_proto_reporting_v1_reporting_proto_rawDescOnce.Do(func() {
		file_proto_reporting_v1_reporting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reporting_v1_reporting_proto_rawDesc), len(file_proto_reporting_v1_reporting_proto_rawDesc)))
	})
	return file_proto_reporting_v1_reporting_proto_rawDescData
}

var file_proto_reporting_v1_reporting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_reporting_v1_reporting_proto_goTypes = []any{
	(*GetAccountSummaryRequest)(nil),  // 0: reporting.v1.GetAccountSummaryRequest
	(*GetAccountSummaryResponse)(nil), // 1: reporting.v1.GetAccountSummaryResponse
}
var file_proto_reporting_v1_reporting_proto_depIdxs = []int32{
	0, // 0: reporting.v1.ReportingService.GetAccountSummary:input_type -> reporting.v1.GetAccountSummaryRequest
	1, // 1: reporting.v1.ReportingService.GetAccountSummary:output_type -> reporting.v1.GetAccountSummaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_reporting_v1_reporting_proto_init() }
func file_proto_reporting_v1_reporting_proto_init() {
	if File_proto_reporting_v1_reporting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reporting_v1_reporting_proto_rawDesc), len(file_proto_reporting_v1_reporting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reporting_v1_reporting_proto_goTypes,
		DependencyIndexes: file_proto_reporting_v1_reporting_proto_depIdxs,
		MessageInfos:      file_proto_reporting_v1_reporting_proto_msgTypes,
	}.Build()
	File_proto_reporting_v1_reporting_proto = out.File
	file_proto_reporting_v1_reporting_proto_goTypes = nil
	file_proto_reporting_v1_reporting_proto_depIdxs = nil
}
